---

#Login and Start
- name: Start docker on boot
  become: yes
  systemd:
    name: docker
    state: started
    enabled: yes

#strt kubelet
- name: start kubelet
  become: yes
  service:
    name: kubelet
    enabled: yes
    state: started

#minikube
- name: Check Minikube status
  command: minikube status
  register: minikube_status
  changed_when: false
  ignore_errors: true

#Otherwise will start minikube
- name: Start Minikube
  become: yes
  command: minikube start
  when: "not minikube_status.stdout or 'Running' not in minikube_status.stdout"