---

#Deployment Pods

- name: status
  shell: kubectl get all --namespace="{{namespace}}"
  register: allstatus
  tags: status

- debug: var=allstatus
  tags: status

#Start Docker
- name: Start docker on boot
  become: yes
  systemd:
    name: docker
    state: started
    enabled: yes
  register: dockerstart
  tags: check

- debug: var=dockerstart
  tags: check

#Login
- name: Log DockerHub
  become: yes
  docker_login:
    username: "{{docker_login}}"
    password: "{{docker_pass}}"
  register: dockerlog
  tags: check

- debug: var=dockerlog
  tags: check

#minikube
- name: Check Minikube
  command: minikube status
  register: minikube_status
  changed_when: false
  ignore_errors: true
  tags: check

#Otherwise will start minikube
- name: Start Minikube
  command: minikube start
  when: "not minikube_status.stdout or 'Running' not in minikube_status.stdout"
  register: ministart
  tags: check

- debug: var=ministart
  tags: check